# Generated by Django 3.0.2 on 2020-01-26 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('post_type', models.CharField(max_length=10)),
                ('brief', models.TextField()),
                ('text', models.TextField()),
                ('url', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 1, 26, 12, 45, 43, 633926, tzinfo=utc))),
                ('cover', models.FilePathField()),
            ],
        ),
    ]
