# Generated by Django 3.0.2 on 2020-01-31 01:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200126_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 1, 31, 1, 7, 44, 85092, tzinfo=utc)),
        ),
    ]
